language: java
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
  - master
before_install: bash etc/ci-setup.sh
install: true
script: eval $TEST_CMD
after_script: if [ -n "$HEROKU_API_KEY" ]; then heroku keys:remove $USER@`hostname`; fi
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - TEST_CMD='bash etc/hatchet.sh'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
